from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddEdgePage(object):
    def setupUi(self, AddEdgePage):
        AddEdgePage.setObjectName("AddEdgePage")
        AddEdgePage.resize(333, 258)
        self.centralwidget = QtWidgets.QWidget(AddEdgePage)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.firstnode = QtWidgets.QComboBox(self.centralwidget)
        self.firstnode.setGeometry(QtCore.QRect(170, 20, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.firstnode.setFont(font)
        self.firstnode.setObjectName("firstnode")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 120, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.edgeweight = QtWidgets.QSpinBox(self.centralwidget)
        self.edgeweight.setGeometry(QtCore.QRect(170, 120, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.edgeweight.setFont(font)
        self.edgeweight.setObjectName("edgeweight")
        self.secondnode = QtWidgets.QComboBox(self.centralwidget)
        self.secondnode.setGeometry(QtCore.QRect(170, 70, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.secondnode.setFont(font)
        self.secondnode.setObjectName("secondnode")
        self.confirmaddedge = QtWidgets.QPushButton(self.centralwidget)
        self.confirmaddedge.setGeometry(QtCore.QRect(170, 170, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.confirmaddedge.setFont(font)
        self.confirmaddedge.setObjectName("confirmaddedge")
        AddEdgePage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AddEdgePage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 333, 21))
        self.menubar.setObjectName("menubar")
        AddEdgePage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AddEdgePage)
        self.statusbar.setObjectName("statusbar")
        AddEdgePage.setStatusBar(self.statusbar)

        self.retranslateUi(AddEdgePage)
        QtCore.QMetaObject.connectSlotsByName(AddEdgePage)

    def retranslateUi(self, AddEdgePage):
        _translate = QtCore.QCoreApplication.translate
        AddEdgePage.setWindowTitle(_translate("AddEdgePage", "Add Edge"))
        self.label_3.setText(_translate("AddEdgePage", "First Node"))
        self.label_4.setText(_translate("AddEdgePage", "Second Node"))
        self.label_5.setText(_translate("AddEdgePage", "Weight"))
        self.confirmaddedge.setText(_translate("AddEdgePage", "Add"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddEdgePage = QtWidgets.QMainWindow()
    ui = Ui_AddEdgePage()
    ui.setupUi(AddEdgePage)
    AddEdgePage.show()
    sys.exit(app.exec_())