from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainGraph(object):
    def setupUi(self, mainGraph):
        mainGraph.setObjectName("mainGraph")
        mainGraph.resize(962, 724)
        self.centralwidget = QtWidgets.QWidget(mainGraph)
        self.centralwidget.setObjectName("centralwidget")
        self.addNode = QtWidgets.QPushButton(self.centralwidget)
        self.addNode.setGeometry(QtCore.QRect(740, 60, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.addNode.setFont(font)
        self.addNode.setObjectName("addNode")
        self.addEdge = QtWidgets.QPushButton(self.centralwidget)
        self.addEdge.setGeometry(QtCore.QRect(740, 120, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.addEdge.setFont(font)
        self.addEdge.setObjectName("addEdge")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(740, 360, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.ChooseSearch = QtWidgets.QComboBox(self.centralwidget)
        self.ChooseSearch.setGeometry(QtCore.QRect(740, 420, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ChooseSearch.setFont(font)
        self.ChooseSearch.setObjectName("ChooseSearch")
        self.ChooseSearch.addItem("")
        self.ChooseSearch.addItem("")
        self.ChooseSearch.addItem("")
        self.ChooseSearch.addItem("")
        self.ChooseSearch.addItem("")
        self.ChooseSearch.addItem("")
        self.ChooseSearch.addItem("")
        self.Submit = QtWidgets.QPushButton(self.centralwidget)
        self.Submit.setGeometry(QtCore.QRect(740, 490, 211, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Submit.setFont(font)
        self.Submit.setObjectName("Submit")
        self.GraphTypeLabel = QtWidgets.QLabel(self.centralwidget)
        self.GraphTypeLabel.setGeometry(QtCore.QRect(780, 0, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.GraphTypeLabel.setFont(font)
        self.GraphTypeLabel.setObjectName("GraphTypeLabel")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 570, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.visitedLabel = QtWidgets.QLabel(self.centralwidget)
        self.visitedLabel.setGeometry(QtCore.QRect(170, 570, 561, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.visitedLabel.setFont(font)
        self.visitedLabel.setObjectName("visitedLabel")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 620, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.solutionPathLabel = QtWidgets.QLabel(self.centralwidget)
        self.solutionPathLabel.setGeometry(QtCore.QRect(170, 620, 561, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.solutionPathLabel.setFont(font)
        self.solutionPathLabel.setObjectName("solutionPathLabel")
        self.BackButton = QtWidgets.QPushButton(self.centralwidget)
        self.BackButton.setGeometry(QtCore.QRect(740, 620, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.BackButton.setFont(font)
        self.BackButton.setObjectName("BackButton")
        self.startState = QtWidgets.QComboBox(self.centralwidget)
        self.startState.setGeometry(QtCore.QRect(740, 220, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.startState.setFont(font)
        self.startState.setObjectName("startState")
        self.GraphTypeLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.GraphTypeLabel_2.setGeometry(QtCore.QRect(800, 180, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.GraphTypeLabel_2.setFont(font)
        self.GraphTypeLabel_2.setObjectName("GraphTypeLabel_2")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(10, 10, 721, 561))
        self.graphicsView.setObjectName("graphicsView")
        self.graphView = QtWidgets.QLabel(self.centralwidget)
        self.graphView.setGeometry(QtCore.QRect(20, 20, 701, 541))
        self.graphView.setText("")
        self.graphView.setObjectName("graphView")
        self.confirmSetStart = QtWidgets.QPushButton(self.centralwidget)
        self.confirmSetStart.setGeometry(QtCore.QRect(850, 220, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.confirmSetStart.setFont(font)
        self.confirmSetStart.setObjectName("confirmSetStart")
        self.confirmAddGoal = QtWidgets.QPushButton(self.centralwidget)
        self.confirmAddGoal.setGeometry(QtCore.QRect(850, 300, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.confirmAddGoal.setFont(font)
        self.confirmAddGoal.setObjectName("confirmAddGoal")
        self.GraphTypeLabel_3 = QtWidgets.QLabel(self.centralwidget)
        self.GraphTypeLabel_3.setGeometry(QtCore.QRect(790, 260, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.GraphTypeLabel_3.setFont(font)
        self.GraphTypeLabel_3.setObjectName("GraphTypeLabel_3")
        self.goalState = QtWidgets.QComboBox(self.centralwidget)
        self.goalState.setGeometry(QtCore.QRect(740, 300, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.goalState.setFont(font)
        self.goalState.setObjectName("goalState")
        mainGraph.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainGraph)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 962, 21))
        self.menubar.setObjectName("menubar")
        mainGraph.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainGraph)
        self.statusbar.setObjectName("statusbar")
        mainGraph.setStatusBar(self.statusbar)

        self.retranslateUi(mainGraph)
        QtCore.QMetaObject.connectSlotsByName(mainGraph)

    def retranslateUi(self, mainGraph):
        _translate = QtCore.QCoreApplication.translate
        mainGraph.setWindowTitle(_translate("mainGraph", "Search Graph"))
        self.addNode.setText(_translate("mainGraph", "Add Node"))
        self.addEdge.setText(_translate("mainGraph", "Add Edge"))
        self.label.setText(_translate("mainGraph", "Choose your search"))
        self.ChooseSearch.setItemText(0, _translate("mainGraph", "Breadth First"))
        self.ChooseSearch.setItemText(1, _translate("mainGraph", "Depth First"))
        self.ChooseSearch.setItemText(2, _translate("mainGraph", "Uniform Cost"))
        self.ChooseSearch.setItemText(3, _translate("mainGraph", "Depth Limited"))
        self.ChooseSearch.setItemText(4, _translate("mainGraph", "Iterative Deepening"))
        self.ChooseSearch.setItemText(5, _translate("mainGraph", "Greedy Best First"))
        self.ChooseSearch.setItemText(6, _translate("mainGraph", "A Star"))
        self.Submit.setText(_translate("mainGraph", "Submit"))
        self.GraphTypeLabel.setText(_translate("mainGraph", "Main Graph"))
        self.label_3.setText(_translate("mainGraph", "Visited:"))
        self.visitedLabel.setText(_translate("mainGraph", "[]"))
        self.label_5.setText(_translate("mainGraph", "Solution Path:"))
        self.solutionPathLabel.setText(_translate("mainGraph", "[]"))
        self.BackButton.setText(_translate("mainGraph", "Back"))
        self.GraphTypeLabel_2.setText(_translate("mainGraph", "Start State"))
        self.confirmSetStart.setText(_translate("mainGraph", "Set Start"))
        self.confirmAddGoal.setText(_translate("mainGraph", "Add Goal"))
        self.GraphTypeLabel_3.setText(_translate("mainGraph", "Goal State(s)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainGraph = QtWidgets.QMainWindow()
    ui = Ui_mainGraph()
    ui.setupUi(mainGraph)
    mainGraph.show()
    sys.exit(app.exec_())
